FROM python:3.11-bookworm

WORKDIR /code

ENV APP_ENV="production"

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . /code

EXPOSE 8001