services:

  service:
    build:
      context: .
      dockerfile: dockerfile

    container_name: calmrr-cheating-service

    ports:
      - "8001:8001"

    environment:
      APP_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BACKEND_URL: "http://172.31.0.55:8000" # "http://calmrr-backend-1:8000"
      PYTHONUNBUFFERED: "1"

    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8001"
      ]

    depends_on:
      - redis

    networks:
      - service_default


  redis:
    image: redis:7

    container_name: calmrr-redis

    restart: unless-stopped

    volumes:
      - redis_data:/data

    networks:
      - service_default


volumes:
  redis_data:


networks:
  service_default: